#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="Robin Manhas(111463105 rmanhas@cs.stonybrook.edu), Harsh Gupta(111470974 hagupta@cs.stonybrook.edu), Shweta Sahu(111481846 shsahu@cs.stonybrook.edu)"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
